import Head from 'next/head'
import * as React from 'react';
import type { NextPage } from 'next';
import Image from 'next/image';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box'
import {useTheme}from '@mui/material/styles';
import { useEffect, useState } from 'react';


export default function Home() {
  const theme = useTheme()
  // console.log(theme)
  
    const [weather, setWeather] = useState([]);
    const [location, setLocation] = useState<undefined | { latitude: number, longitude: number }>(undefined);
   
    const options = {
      method: 'GET',
      headers: {
        'X-RapidAPI-Key': 'c3c48d1f5emsh1d70c25085a9a06p1554d6jsnce958caf6dab',
        'X-RapidAPI-Host': 'weatherapi-com.p.rapidapi.com'
      }
    };

    useEffect(() => {
        if('geolocation' in navigator) {
            // Retrieve latitude & longitude coordinates from `navigator.geolocation` Web API
            navigator.geolocation.getCurrentPosition(({ coords }) => {
                const { latitude, longitude } = coords;
              console.log({ coords });
                setLocation({ latitude, longitude });
            })
        }
    }, []);

    useEffect(() => {
        // Fetch data from API if `location` object is set
        if (location) {
          // here 
          const url = `https://weatherapi-com.p.rapidapi.com/current.json?q=${location.latitude}%2${location.longitude}`

          fetch(url, options)
	          .then(res => res.json())
	          .then(json => setWeather(json))
	          .catch(err => console.error('error:' + err));

        }
      console.log({location});
    }, [location]);
  console.log({ weather });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth='lg'>
        <Box
        sx={{
          my: 5,
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'start',
          bgcolor: "rgba(255, 255, 255, 0.1)",
          width: "fit-content",
          padding: "12px 37px 18px 28px"
        }}
      >
        <Typography component='p' color='common.white'>
          Sat 22
        </Typography>
  

        <Box sx={{width: "fit-content",display:"flex", gap:'7px'}}>
        <Image height="64" width="64" alt='' src="http://cdn.weatherapi.com/weather/64x64/day/116.png"/>
        <Box sx={{display: 'flex', flexDirection:'column'}}>
        <Typography sx={{fontWeight:"600"}} component='p' color='common.white'>
          56°
        </Typography>
        <Typography  component='p' color='common.white'>
          46°
        </Typography>
        </Box>
        </Box>

      </Box>
    </Container>
    </>
  )
}
